function addBadges(){var t=document.querySelector('div.w-wrapper.product-description');if(!t||document.querySelector('.rb'))return;var s=document.createElement('style');s.textContent='.rb{display:flex;flex-wrap:wrap;gap:10px;padding:16px 0;margin:0 0 14px;border-top:1px solid #e8e0d8;border-bottom:1px solid #e8e0d8}.rb>div{display:flex;align-items:center;gap:10px;flex:1;min-width:130px}.rb em{font-size:20px;font-style:normal}.rb b{display:block;font-size:11px;font-weight:600;color:#1a1a1a;letter-spacing:.06em;text-transform:uppercase}.rb span{font-size:11px;color:#999;font-style:italic}';document.head.appendChild(s);var d=document.createElement('div');d.className='rb';d.innerHTML='<div><em>✔️</em><div><b>100% Authentique</b><span>Fragrances certifiées</span></div></div><div><em>🎁</em><div><b>Échantillons offerts</b><span>Emballage premium inclus</span></div></div><div><em>🚚</em><div><b>Livraison soignée</b><span>Expédition rapide</span></div></div><div><em>🔒</em><div><b>Paiement sécurisé</b><span>SSL & 3D Secure</span></div></div>';t.parentNode.insertBefore(d,t);}

function addFaq(){var t=document.querySelector('div.w-wrapper.product-description');if(!t||document.querySelector('.pfaq'))return;var s=document.createElement('style');s.textContent='.pfaq{margin:16px 0;border-top:1px solid #e8e0d8}.pfaq .fq{border-bottom:1px solid #e8e0d8}.pfaq .fqt{padding:12px 0;font-size:11px;letter-spacing:.07em;text-transform:uppercase;font-weight:600;color:#1a1a1a;cursor:pointer;display:flex;justify-content:space-between;align-items:center}.pfaq .fqa{font-size:12px;color:#666;line-height:1.7;font-style:italic;max-height:0;overflow:hidden;transition:max-height .3s ease}.pfaq .fqa.open{max-height:200px;padding-bottom:12px}';document.head.appendChild(s);var items=[['Quelle est la tenue ?','Nos parfums de niche ont une concentration supérieure (20–35%). Comptez 6 à 12h de tenue selon votre peau et les conditions.'],['Ce parfum est-il mixte ?','Nos créations sont conçues sans genre. La perception varie selon la chimie de chaque peau.'],['Comment conserver mon parfum ?','À l\'abri de la lumière et de la chaleur, idéalement dans son écrin. Un parfum bien conservé se garde 3 à 5 ans.'],['Puis-je retourner mon article ?','Oui, sous 14 jours si la boite et le flacon sont intacts et non ouverts. Contactez-nous et nous trouverons une solution.']];var html='<div class="pfaq">';items.forEach(function(i){html+='<div class="fq"><div class="fqt">'+i[0]+'<span>＋</span></div><div class="fqa">'+i[1]+'</div></div>';});html+='</div>';var d=document.createElement('div');d.innerHTML=html;t.parentNode.insertBefore(d.firstChild,t.nextSibling);document.querySelectorAll('.fqt').forEach(function(el){el.addEventListener('click',function(){var a=this.nextElementSibling,s=this.querySelector('span');a.classList.toggle('open');s.textContent=a.classList.contains('open')?'－':'＋';});});}

function addGarantie(){var t=document.querySelector('div.w-wrapper.product-description');if(!t||document.querySelector('.pgar'))return;var s=document.createElement('style');s.textContent='.pgar{background:#faf7f4;border:1px solid #e8e0d8;border-radius:8px;padding:16px;margin:16px 0}.pgar h4{font-size:11px;letter-spacing:.08em;text-transform:uppercase;font-weight:600;color:#1a1a1a;margin:0 0 12px}.pgar>div{display:flex;flex-direction:column;gap:10px}.pgar li{display:flex;align-items:flex-start;gap:10px;font-size:12px;color:#555;line-height:1.5;list-style:none}.pgar em{font-size:18px;font-style:normal;flex-shrink:0}';document.head.appendChild(s);var d=document.createElement('div');d.className='pgar';d.innerHTML='<h4>Notre engagement</h4><div><li><em>✨</em><span><strong style="color:#1a1a1a">Parfumerie de niche authentique</strong> — chaque fragrance est sélectionnée pour son caractère unique et sa qualité de composition.</span></li><li><em>📦</em><span><strong style="color:#1a1a1a">Expédition sous 24h</strong> — votre colis est emballé avec soin dans un écrin protecteur, prêt à être offert.</span></li><li><em>↩️</em><span><strong style="color:#1a1a1a">Retour sous 14 jours</strong> — si vous n\'êtes pas pleinement satisfait, nous vous remboursons.</span></li></div>';t.parentNode.insertBefore(d,t.nextSibling);}

function addVideo(){var t=document.querySelector('.pgar');if(!t||document.querySelector('.pvid'))return;var s=document.createElement('style');s.textContent='.pvid{margin:16px 0}.pvid p{font-size:11px;letter-spacing:.08em;text-transform:uppercase;font-weight:600;color:#1a1a1a;margin:0 0 10px;text-align:center}.pvid .fr{max-width:360px;margin:0 auto;border-radius:12px;overflow:hidden;border:1px solid #e8e0d8;aspect-ratio:9/16;position:relative}.pvid iframe{width:100%;height:100%;border:none;position:absolute;top:0;left:0}@media(max-width:600px){.pvid .fr{max-width:100%}}';document.head.appendChild(s);var d=document.createElement('div');d.className='pvid';d.innerHTML='<p>✦ Notre univers</p><div class="fr"></div>';t.parentNode.insertBefore(d,t);var fr=d.querySelector('.fr');new IntersectionObserver(function(en){en.forEach(function(e){if(e.isIntersecting&&!fr.querySelector('iframe')){var f=document.createElement('iframe');f.src='https://iframe.cloudflarestream.com/b54b0d2d8ae301523c65ad408f366b55?autoplay=true&muted=true&loop=true&controls=false&preload=none';f.allow='autoplay;fullscreen';fr.appendChild(f);}else if(!e.isIntersecting&&fr.querySelector('iframe')){fr.querySelector('iframe').src='';}});},{threshold:0.3}).observe(d);}

function run(){
  var t=document.querySelector('div.w-wrapper.product-description');
  if(!t)return;
  addBadges();addFaq();addGarantie();
  setTimeout(addVideo,300);
}

new MutationObserver(function(){
  var t=document.querySelector('div.w-wrapper.product-description');
  if(t&&!document.querySelector('.rb'))run();
}).observe(document.body,{childList:true,subtree:true});
